### ISSUE TITLE
Horizontal Scene selector (knob 8) is not working in Ableton 12

### ISSUE THREAD

**Issue by ManuelR-D** [DeepSmeag/MinilabMk2-Ableton-script#13]
Hi! First of all, amazing project.

I saw that this remote script has a version for Ableton 10 and 11 but not 12, so I tested it on 12. Everything worked fine except for the horizontal scene selector. The Knob 8 only moves 1 position to the right in the scene selector regardless of how much it is rotated (clockwise), however it seems to be working fine when moving to the left (counter clockwise).

 I've fixed it by changing the midi control mode in the source code. I pushed this PR https://github.com/DeepSmeag/MinilabMk2-Ableton-script/pull/12 with the fix.

**Comment by DeepSmeag** [comment]
Merged the PR, thank you @ManuelR-D
