### ISSUE TITLE
Encoder 8 scrolling issue

### ISSUE THREAD

**Issue by Prujirou** [DeepSmeag/MinilabMk2-Ableton-script#7]
When I use Encoder 8 to scroll it only scrolls one column and no further. Also it scrolls to the left when I turn to the right and vice versa. 
Hope this is the right section for something like this, thank you for your work!

**Comment by DeepSmeag** [comment]
I remember an issue like this back when I was testing various options. Open Midi Control Center, select the knob, and try options like Absolute or Relative.
Let me know if this fixes it, I don't think the problem is with the script.

**Comment by Prujirou** [comment]
Oof I feel stupid. Changing knob 8 to Relative #1 did the trick. Thank you so much and thanks again for having done this in general. Huge help!
